language: php

before_script:
  - curl -L https://github.com/rqlite/rqlite/releases/download/v7.21.4/rqlite-v7.21.4-linux-amd64.tar.gz -o rqlite-v7.21.4-linux-amd64.tar.gz
  - tar xvfz rqlite-v7.21.4-linux-amd64.tar.gz
  - cd rqlite-v7.21.4-linux-amd64
  - ./rqlited ~/node.1 &
  - cd ..
  - sleep 5

php:
  - '7.4'
  - '8.1'

matrix:
  include:
    - php: 8.2
      dist: jammy # Version 8.2 is not available in the "bionic", newer version is required.

script: phpunit
