CREATE TABLE groups (id INTEGER NOT NULL PRIMARY KEY,name TEXT NOT NULL)
INSERT INTO groups (name) VALUES("Servers")
ALTER TABLE services ADD groupID INTEGER REFERENCES groups(id)
UPDATE services SET groupID = 1
